import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/nav-bar";

const poppins = Poppins( {
  subsets: [ 'latin' ],
  weight: [ '400', '600', '700' ],
} );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en">
      <body className={ `${poppins.className} antialiased` }>
        <div className="min-h-screen bg-green-50">

          <header className="bg-gradient-to-r from-green-700 to-[#f9c970] text-white text-center py-4">
            <h1 className="text-xl font-semibold">
              Desenvolvimento Sustentável na Produção de Alimentos
            </h1>
          </header>

          <Navbar />

          { children }

        </div>
      </body>
    </html>
  );
}
