import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Navbar } from "./components/nav-bar";

const geistSans = Geist( {
  variable: "--font-geist-sans",
  subsets: [ "latin" ],
} );

const geistMono = Geist_Mono( {
  variable: "--font-geist-mono",
  subsets: [ "latin" ],
} );

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout ( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> ) {
  return (
    <html lang="en">
      <body className={ `${geistSans.variable} ${geistMono.variable} antialiased` }>
        <div className="min-h-screen bg-green-50">

          <header className="bg-gradient-to-r from-green-700 to-[#f9c970] text-white text-center py-4">
            <h1 className="text-xl font-semibold italic">
              Desenvolvimento Sustentável na Produção de Alimentos
            </h1>
          </header>

          <Navbar />

          { children }

        </div>
      </body>
    </html>
  );
}
